//! Full-resolution gradient-based (VNG) demosaic.
//!
//! Classic eight-direction "variable number of gradients" interpolation over a
//! 5×5 window. Around every interior CFA site eight directional gradients are
//! measured; the directions whose gradient falls under an adaptive threshold are
//! kept, and the missing colours are estimated from those directions only — so
//! interpolation follows edges instead of averaging across them. The count of
//! kept directions varies per pixel, which is what the name refers to.
//!
//! Each kept direction contributes one full colour triple, read at its immediate
//! neighbour: that neighbour holds a real sample of exactly one colour, so the
//! other two come from the bilinear estimate there, while the centre's own colour
//! is the mean of the centre and the sample two steps out. The estimate is then
//! `centre + (mean of colour c) − (mean of the centre's colour)`, a difference of
//! means that cancels the interpolation bias common to both.
//!
//! An earlier form averaged a fixed arm of offsets per direction. It is provably
//! identical to the above at red and blue sites — each arm reduces to exactly
//! these samples — so it is not a cheaper spelling of the same thing: it differs
//! only at green sites, and there it measured worse against the external
//! reference (plane 0 corr 0.9947 vs 0.9968, p99.9 2.9e-3 vs 1.2e-3).
//!
//! Unlike [`super::debayer::super_pixel_debayer_f32`] this keeps the native
//! pixel grid: the output is a full-resolution planar RGB buffer.
//!
//! Validated against an external reference implementation's VNG output for the
//! same calibrated CFA frame by `vng_matches_reference_debayer` below.
//!
//! The interior pass (this module's hot loop) is parallelized with rayon over
//! horizontal row bands, each computed by [`interior_pixel_rgb`] — the single
//! per-pixel function both the parallel loop and the `#[cfg(test)]` serial
//! reference call, so splitting rows across threads changes only which core
//! writes a pixel, never the arithmetic that produces its value, keeping the
//! output bit-identical to a fully serial run; the O(width+height) border pass
//! ([`bilinear_border`]) stays serial.

use crate::types::BayerPattern;
use rayon::prelude::*;

/// Unit vectors of the eight directions: the four axial ones first, then the four
/// diagonals. They are both the gradient directions and the offsets of the eight
/// neighbours a selected direction reads its colour triple from. The gradient
/// table is generated by rotating one canonical form (north for axial, north-east
/// for diagonal) onto these vectors, so all eight stay consistent by construction.
const DIRECTIONS: [(i32, i32); 8] = [
    (0, -1),  // N
    (1, 0),   // E
    (0, 1),   // S
    (-1, 0),  // W
    (1, -1),  // NE
    (1, 1),   // SE
    (-1, 1),  // SW
    (-1, -1), // NW
];

/// Half of the eight directions are diagonal; the first four are axial.
const FIRST_DIAGONAL: usize = 4;

/// Sample pairs per direction whose absolute differences form its gradient.
const GRADIENT_TERMS: usize = 6;

/// Row-band height for the parallel interior pass. Each band is one rayon
/// task, so it must comfortably clear task-dispatch overhead (kept well above
/// the 32-row floor); at the same time a full-height frame should still split
/// into many more bands than there are cores, so rayon's work-stealing can
/// balance heterogeneous cores on its own — without hand-tuned per-core
/// weights — and the tail (last, possibly partial) band stays a small
/// fraction of the total work.
const BAND_ROWS: usize = 64;

/// The first two gradient terms carry full weight, the remaining four a half
/// weight — they sit one pixel off the direction's own axis.
const FULL_WEIGHT_TERMS: usize = 2;

type Offset = (i32, i32);

/// For each direction, the six `(a, b)` offset pairs contributing `|p(a) − p(b)|`
/// to its gradient. Entries `0..FULL_WEIGHT_TERMS` count at weight 1, the rest at
/// weight 0.5 — they sit one pixel off the direction's own axis.
///
/// A pair whose two samples are DIFFERENT colours is skipped at use time, and the
/// surviving weights are renormalised (see [`vng_debayer_f32`]). The first two
/// pairs are always same-colour, so a gradient never loses every term; the ones
/// that do get skipped are the four half-weight pairs of a diagonal at a green
/// site, where a diagonal step maps red onto blue and no same-colour pair exists.
/// Keeping them would measure the red/blue colour difference rather than local
/// detail, which swamps the gradient and leaves a green site's diagonals
/// permanently outvoted — measured against the external reference, skipping and
/// renormalising cut the median error by four orders of magnitude.
fn gradient_terms() -> [[(Offset, Offset); GRADIENT_TERMS]; 8] {
    let mut terms = [[((0, 0), (0, 0)); GRADIENT_TERMS]; 8];
    for (d, &(ux, uy)) in DIRECTIONS.iter().enumerate() {
        let two = (ux * 2, uy * 2);
        terms[d] = if d < FIRST_DIAGONAL {
            // Axial: `q` is the direction turned 90°, so the four half-weight
            // terms repeat the axial difference on the two flanking columns.
            let (qx, qy) = (-uy, ux);
            [
                ((ux, uy), (-ux, -uy)),
                (two, (0, 0)),
                ((ux + qx, uy + qy), (-ux + qx, -uy + qy)),
                ((ux - qx, uy - qy), (-ux - qx, -uy - qy)),
                ((two.0 + qx, two.1 + qy), (qx, qy)),
                ((two.0 - qx, two.1 - qy), (-qx, -qy)),
            ]
        } else {
            // Diagonal: `a` and `b` are the direction's horizontal and vertical
            // components, and the half-weight terms step along the two staircases
            // flanking the diagonal.
            let (a, b) = ((ux, 0), (0, uy));
            [
                ((ux, uy), (-ux, -uy)),
                (two, (0, 0)),
                ((ux + b.0, uy + b.1), b),
                ((ux + a.0, uy + a.1), a),
                (b, (-a.0, -a.1)),
                (a, (-b.0, -b.1)),
            ]
        };
    }
    terms
}

/// Colour index (0 = R, 1 = G, 2 = B) of each of the four CFA sites in the
/// pattern's 2×2 tile, indexed by `(y & 1) * 2 + (x & 1)`.
fn tile_colors(pattern: BayerPattern) -> [usize; 4] {
    match pattern {
        BayerPattern::Rggb => [0, 1, 1, 2],
        BayerPattern::Bggr => [2, 1, 1, 0],
        BayerPattern::Grbg => [1, 0, 2, 1],
        BayerPattern::Gbrg => [1, 2, 0, 1],
        BayerPattern::None => [0, 0, 0, 0],
    }
}

/// Full-resolution gradient-based demosaic. Input: one CFA plane, row-major,
/// any float scale (negatives allowed). Output: PLANAR RGB, len `3 * width * height`,
/// ordered `[R plane | G plane | B plane]`. `pattern` must not be
/// [`BayerPattern::None`] — a `None` pattern replicates the input into all three
/// planes rather than guessing a mosaic.
pub fn vng_debayer_f32(
    data: &[f32],
    width: usize,
    height: usize,
    pattern: BayerPattern,
) -> Vec<f32> {
    debug_assert!(
        pattern != BayerPattern::None,
        "vng_debayer_f32 needs a real Bayer pattern"
    );
    debug_assert_eq!(data.len(), width * height, "CFA plane length");

    let plane = width * height;
    let mut out = vec![0f32; 3 * plane];
    if pattern == BayerPattern::None {
        for p in 0..3 {
            out[p * plane..][..plane].copy_from_slice(&data[..plane]);
        }
        return out;
    }

    let colors = tile_colors(pattern);

    // Interior = every site with a full 5×5 window. `saturating_sub` keeps the
    // range empty (rather than panicking) on images narrower/shorter than that.
    let x_hi = width.saturating_sub(2);
    let y_hi = height.saturating_sub(2);

    bilinear_border(data, width, height, &colors, x_hi, y_hi, &mut out);

    let terms = gradient_terms();

    // Split the interior rows [2, y_hi) out of all three planes and hand each
    // plane's row bands to rayon in lock-step (`zip`), so every band writes
    // disjoint mutable slices of R, G and B — no `unsafe`, no `Mutex`. Each
    // pixel only reads `data` (shared, immutable) and calls
    // `interior_pixel_rgb`, so which thread computes which band cannot change
    // a single output value.
    let interior_rows = y_hi.saturating_sub(2);
    if interior_rows > 0 && width > 0 {
        let row_lo = 2 * width;
        let row_hi = y_hi * width;
        let (r_plane, rest) = out.split_at_mut(plane);
        let (g_plane, b_plane) = rest.split_at_mut(plane);
        let band_elems = BAND_ROWS * width;

        r_plane[row_lo..row_hi]
            .par_chunks_mut(band_elems)
            .zip(g_plane[row_lo..row_hi].par_chunks_mut(band_elems))
            .zip(b_plane[row_lo..row_hi].par_chunks_mut(band_elems))
            .enumerate()
            .for_each(|(band_idx, ((r_band, g_band), b_band))| {
                let y_start = 2 + band_idx * BAND_ROWS;
                // The last band may be shorter than `BAND_ROWS`; every chunk's
                // length is still an exact multiple of `width`.
                let rows_in_band = r_band.len() / width;
                for local_y in 0..rows_in_band {
                    let y = y_start + local_y;
                    let row = local_y * width;
                    for x in 2..x_hi {
                        let rgb = interior_pixel_rgb(data, width, height, &colors, &terms, x, y);
                        r_band[row + x] = rgb[0];
                        g_band[row + x] = rgb[1];
                        b_band[row + x] = rgb[2];
                    }
                }
            });
    }

    out
}

/// The full VNG-interpolated RGB triple at one interior CFA site (a site with
/// a complete 5×5 window). Used by both the parallel interior pass above and
/// the `#[cfg(test)]` serial reference — the shared function is what makes
/// band-splitting provably bit-identical: there is only one place the
/// per-pixel arithmetic is written.
fn interior_pixel_rgb(
    data: &[f32],
    width: usize,
    height: usize,
    colors: &[usize; 4],
    terms: &[[(Offset, Offset); GRADIENT_TERMS]; 8],
    x: usize,
    y: usize,
) -> [f32; 3] {
    let color_at = |x: usize, y: usize| colors[(y & 1) * 2 + (x & 1)];

    let center = y * width + x;
    let base = data[center];
    let center_color = color_at(x, y);

    let sample = |dx: i32, dy: i32| -> f32 {
        data[(y as i32 + dy) as usize * width + (x as i32 + dx) as usize]
    };

    let mut gradients = [0f32; 8];
    // Weighted MEAN, not sum, of the same-colour difference terms: a
    // direction that had to drop cross-colour pairs must stay comparable
    // with one that kept all six. `wsum` is never zero — the first two
    // terms of every direction are same-colour by construction.
    for (d, dir_terms) in terms.iter().enumerate() {
        let mut g = 0f32;
        let mut wsum = 0f32;
        for (t, &((ax, ay), (bx, by))) in dir_terms.iter().enumerate() {
            if color_at((x as i32 + ax) as usize, (y as i32 + ay) as usize)
                != color_at((x as i32 + bx) as usize, (y as i32 + by) as usize)
            {
                continue;
            }
            let w = if t < FULL_WEIGHT_TERMS { 1.0 } else { 0.5 };
            g += w * (sample(ax, ay) - sample(bx, by)).abs();
            wsum += w;
        }
        gradients[d] = g / wsum;
    }

    let mut g_min = gradients[0];
    let mut g_max = gradients[0];
    for &g in &gradients[1..] {
        if g < g_min {
            g_min = g;
        }
        if g > g_max {
            g_max = g;
        }
    }
    // Equal min and max (a flat neighbourhood) admits all eight.
    let threshold = 1.5 * g_min + 0.5 * (g_max - g_min);

    // Each selected direction contributes one full colour triple, taken
    // from its immediate neighbour. The neighbour only carries one real
    // sample, so the other two colours come from the bilinear estimate
    // there; the centre's OWN colour instead averages the centre with the
    // sample two steps out, which is a real sample of that colour
    // whenever the neighbour is not.
    let mut color_sum = [0f32; 3];
    let mut n_dirs = 0u32;
    for (d, &(ux, uy)) in DIRECTIONS.iter().enumerate() {
        if gradients[d] > threshold {
            continue;
        }
        n_dirs += 1;
        let (nx, ny) = ((x as i32 + ux) as usize, (y as i32 + uy) as usize);
        let (fx, fy) = ((x as i32 + 2 * ux) as usize, (y as i32 + 2 * uy) as usize);
        let neighbour = bilinear_rgb_at(data, width, height, colors, nx, ny);
        // Two steps out keeps both coordinate parities, so it is always a
        // real sample of the centre's own colour. When the neighbour is a
        // different colour, pairing those two beats reading the
        // neighbour's interpolated value for that colour.
        let pair_with_far = color_at(nx, ny) != center_color;
        for c in 0..3 {
            color_sum[c] += if c == center_color && pair_with_far {
                0.5 * (base + data[fy * width + fx])
            } else {
                neighbour[c]
            };
        }
    }

    // At least one direction is always selected: the threshold is never
    // below the smallest gradient, so `n_dirs` is never zero.
    let center_mean = color_sum[center_color] / n_dirs as f32;
    let mut result = [0f32; 3];
    for c in 0..3 {
        result[c] = if c == center_color {
            base
        } else {
            base + (color_sum[c] / n_dirs as f32 - center_mean)
        };
    }
    result
}

/// Bilinear RGB estimate at one CFA site: the site's own sample for its own
/// colour, and for each missing colour the mean of the in-bounds neighbours that
/// carry it — the four cardinal ones (green at a red or blue site; red and blue
/// at a green site) and the four diagonal ones (the colour opposite the centre's).
fn bilinear_rgb_at(
    data: &[f32],
    width: usize,
    height: usize,
    colors: &[usize; 4],
    x: usize,
    y: usize,
) -> [f32; 3] {
    const CARDINAL: [Offset; 4] = [(0, -1), (1, 0), (0, 1), (-1, 0)];
    const DIAGONAL: [Offset; 4] = [(-1, -1), (1, -1), (1, 1), (-1, 1)];
    const GREEN: usize = 1;

    let center_color = colors[(y & 1) * 2 + (x & 1)];
    let base = data[y * width + x];
    let mut sum = [0f32; 3];
    let mut count = [0u32; 3];
    // A green centre finds red and blue on its cardinal neighbours only; a red
    // or blue centre finds green there and its opposite diagonally.
    let extra: &[Offset] = if center_color == GREEN {
        &[]
    } else {
        &DIAGONAL
    };
    for &(dx, dy) in CARDINAL.iter().chain(extra.iter()) {
        let (nx, ny) = (x as i32 + dx, y as i32 + dy);
        if nx < 0 || ny < 0 || nx >= width as i32 || ny >= height as i32 {
            continue;
        }
        let (nx, ny) = (nx as usize, ny as usize);
        let c = colors[(ny & 1) * 2 + (nx & 1)];
        if c == center_color {
            continue;
        }
        sum[c] += data[ny * width + nx];
        count[c] += 1;
    }

    std::array::from_fn(|c| {
        if c == center_color {
            base
        } else if count[c] > 0 {
            sum[c] / count[c] as f32
        } else {
            base
        }
    })
}

/// Bilinear demosaic for the two-pixel frame the 5×5 gradient window cannot reach.
fn bilinear_border(
    data: &[f32],
    width: usize,
    height: usize,
    colors: &[usize; 4],
    x_hi: usize,
    y_hi: usize,
    out: &mut [f32],
) {
    let plane = width * height;
    for y in 0..height {
        for x in 0..width {
            if (2..y_hi).contains(&y) && (2..x_hi).contains(&x) {
                continue;
            }
            let rgb = bilinear_rgb_at(data, width, height, colors, x, y);
            for c in 0..3 {
                out[c * plane + y * width + x] = rgb[c];
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::BayerPattern;

    /// `formats::xisf` multiplies float samples by this to reach the FITS u16
    /// range (R-M4a-11 — the reader's ADU-domain convention stays; it is a
    /// production contract for `athenaeum-core`'s band/analysis readers, not
    /// just a rendering convenience), so a comparison in the file's own
    /// [0, 1] units divides it back out.
    const XISF_FLOAT_SCALE: f64 = 65535.0;

    fn cfa_fill(w: usize, h: usize, pattern: BayerPattern, r: f32, g: f32, b: f32) -> Vec<f32> {
        // Fill a mosaic where every R site = r, G site = g, B site = b for `pattern`.
        let (ri, g0, g1, bi) = match pattern {
            BayerPattern::Rggb => (0, 1, 2, 3),
            BayerPattern::Bggr => (3, 1, 2, 0),
            BayerPattern::Grbg => (1, 0, 3, 2),
            BayerPattern::Gbrg => (2, 3, 0, 1),
            BayerPattern::None => unreachable!(),
        };
        let vals =
            |slot: usize| [r, g, g, b][[ri, g0, g1, bi].iter().position(|&s| s == slot).unwrap()];
        (0..w * h)
            .map(|i| {
                let (x, y) = (i % w, i / w);
                vals((y % 2) * 2 + (x % 2))
            })
            .collect()
    }

    #[test]
    fn constant_channels_reconstruct_exactly() {
        for pattern in [
            BayerPattern::Rggb,
            BayerPattern::Bggr,
            BayerPattern::Grbg,
            BayerPattern::Gbrg,
        ] {
            let (w, h) = (16, 12);
            let cfa = cfa_fill(w, h, pattern, 0.8, 0.5, 0.2);
            let rgb = vng_debayer_f32(&cfa, w, h, pattern);
            assert_eq!(rgb.len(), 3 * w * h);
            for (plane, want) in [(0, 0.8f32), (1, 0.5), (2, 0.2)] {
                for v in &rgb[plane * w * h..(plane + 1) * w * h] {
                    assert!(
                        (v - want).abs() < 1e-6,
                        "{pattern:?} plane {plane}: {v} != {want}"
                    );
                }
            }
        }
    }

    #[test]
    fn horizontal_ramp_stays_monotonic_and_bounded() {
        // A luminance ramp (all channels equal, linear in x) must reconstruct to
        // values within the local input range — no over/undershoot beyond neighbors.
        let (w, h) = (32, 16);
        let cfa: Vec<f32> = (0..w * h).map(|i| (i % w) as f32 / w as f32).collect();
        let rgb = vng_debayer_f32(&cfa, w, h, BayerPattern::Rggb);
        for plane in 0..3 {
            for y in 2..h - 2 {
                for x in 3..w - 3 {
                    let v = rgb[plane * w * h + y * w + x];
                    let lo = (x as f32 - 2.0) / w as f32;
                    let hi = (x as f32 + 2.0) / w as f32;
                    assert!(
                        v >= lo - 1e-5 && v <= hi + 1e-5,
                        "plane {plane} ({x},{y}): {v}"
                    );
                }
            }
        }
    }

    #[test]
    fn negatives_pass_through() {
        let (w, h) = (8, 8);
        let cfa = cfa_fill(w, h, BayerPattern::Rggb, -0.1, -0.1, -0.1);
        let rgb = vng_debayer_f32(&cfa, w, h, BayerPattern::Rggb);
        assert!(rgb.iter().all(|v| (*v - -0.1).abs() < 1e-6));
    }

    /// A straightforward SERIAL copy of `vng_debayer_f32`'s interior pass —
    /// same border call, same nested `y`/`x` loop, same per-pixel helper
    /// (`interior_pixel_rgb`) — kept only so `parallel_matches_serial_reference`
    /// has something to diff the row-banded version against. It must never grow
    /// a second implementation of the per-pixel math; if `interior_pixel_rgb`
    /// changes, this changes with it for free.
    fn vng_debayer_f32_serial_reference(
        data: &[f32],
        width: usize,
        height: usize,
        pattern: BayerPattern,
    ) -> Vec<f32> {
        debug_assert!(pattern != BayerPattern::None);
        debug_assert_eq!(data.len(), width * height);

        let plane = width * height;
        let mut out = vec![0f32; 3 * plane];

        let colors = tile_colors(pattern);
        let x_hi = width.saturating_sub(2);
        let y_hi = height.saturating_sub(2);

        bilinear_border(data, width, height, &colors, x_hi, y_hi, &mut out);

        let terms = gradient_terms();

        for y in 2..y_hi {
            for x in 2..x_hi {
                let rgb = interior_pixel_rgb(data, width, height, &colors, &terms, x, y);
                let center = y * width + x;
                for c in 0..3 {
                    out[c * plane + center] = rgb[c];
                }
            }
        }

        out
    }

    /// Deterministic pseudo-random CFA fill (xorshift64*) so the bit-identity
    /// test below is reproducible without pulling in a `rand` dependency.
    fn pseudo_random_mosaic(w: usize, h: usize, seed: u64) -> Vec<f32> {
        let mut state = if seed == 0 { 0x9E3779B97F4A7C15 } else { seed };
        (0..w * h)
            .map(|_| {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                let frac = ((state >> 40) & 0xFFFF) as f32 / 0xFFFF as f32; // [0, 1]
                frac * 65535.0 // FITS-u16-ish dynamic range
            })
            .collect()
    }

    /// `vng_debayer_f32`'s row-banded parallel interior pass must produce
    /// EXACTLY the same floats as the serial reference — not "close", `==` on
    /// every element. Covers a ≥512×512 mosaic (several full `BAND_ROWS` bands)
    /// and an odd-sized one (517×389 — not a multiple of `BAND_ROWS`, so the
    /// last band is partial and a band boundary lands mid-frame) for two
    /// Bayer patterns.
    #[test]
    fn parallel_matches_serial_reference() {
        for &(w, h) in &[(512usize, 512usize), (517usize, 389usize)] {
            for pattern in [BayerPattern::Rggb, BayerPattern::Gbrg] {
                let seed = 0xC0FF_EE00_u64 ^ (w as u64) ^ ((h as u64) << 32);
                let cfa = pseudo_random_mosaic(w, h, seed);

                let parallel = vng_debayer_f32(&cfa, w, h, pattern);
                let serial = vng_debayer_f32_serial_reference(&cfa, w, h, pattern);

                assert_eq!(parallel.len(), serial.len());
                for (i, (&p, &s)) in parallel.iter().zip(serial.iter()).enumerate() {
                    assert_eq!(
                        p, s,
                        "{pattern:?} {w}x{h}: mismatch at flat index {i} (parallel {p} != serial {s})"
                    );
                }
            }
        }
    }

    /// Compares our VNG against the external reference's debayered output for the
    /// same calibrated CFA input. Set:
    ///   VNG_REF_CAL = path to a calibrated CFA .xisf (single channel, RGGB)
    ///   VNG_REF_DEB = path to the matching debayered .xisf (3 channels)
    /// e.g. the LDN 1272 reference pair
    ///   .../calibrated/Light_..._CFA_.../2025-09-14_00-55-28..._0000_c.xisf
    ///   .../debayered/Light_..._CFA_.../2025-09-14_00-55-28..._0000_c_d.xisf
    ///
    /// `read_xisf_image` normalises interleaved samples to planar before
    /// returning, so both sides are compared plane by plane. It also scales float
    /// samples by [`XISF_FLOAT_SCALE`] to reach the FITS u16 range, so both sides
    /// are divided back out and the thresholds below are in the files' own [0, 1]
    /// units (this frame's mean sits at 6.6e-3 there).
    #[test]
    #[ignore = "needs real reference files via VNG_REF_CAL / VNG_REF_DEB"]
    fn vng_matches_reference_debayer() {
        use crate::formats::xisf::read_xisf_image;
        let cal = std::env::var("VNG_REF_CAL").expect("VNG_REF_CAL");
        let deb = std::env::var("VNG_REF_DEB").expect("VNG_REF_DEB");
        let (mc, pc) = read_xisf_image(std::path::Path::new(&cal)).unwrap();
        let (md, pd) = read_xisf_image(std::path::Path::new(&deb)).unwrap();
        let cfa = match pc {
            crate::types::PixelData::Float32(v) => v,
            _ => panic!("expect f32"),
        };
        let refi = match pd {
            crate::types::PixelData::Float32(v) => v,
            _ => panic!("expect f32"),
        };
        assert_eq!(mc.channels, 1, "calibrated side must be a single CFA plane");
        assert_eq!(md.channels, 3);
        assert_eq!(
            (md.width, md.height),
            (mc.width, mc.height),
            "the two reference files must describe the same frame"
        );
        let (w, h) = (mc.width, mc.height);
        let ours = vng_debayer_f32(&cfa, w, h, crate::types::BayerPattern::Rggb);
        let mut stats = Vec::new();
        for plane in 0..3 {
            // Interior only — border policy legitimately differs.
            let mut diffs: Vec<f64> = Vec::with_capacity((w - 8) * (h - 8));
            let (mut so, mut sr, mut soo, mut srr, mut sor) = (0f64, 0f64, 0f64, 0f64, 0f64);
            for y in 4..h - 4 {
                for x in 4..w - 4 {
                    let o = ours[plane * w * h + y * w + x] as f64 / XISF_FLOAT_SCALE;
                    let r = refi[plane * w * h + y * w + x] as f64 / XISF_FLOAT_SCALE;
                    diffs.push((o - r).abs());
                    so += o;
                    sr += r;
                    soo += o * o;
                    srr += r * r;
                    sor += o * r;
                }
            }
            let n = diffs.len() as f64;
            let corr = (sor - so * sr / n) / (((soo - so * so / n) * (srr - sr * sr / n)).sqrt());
            // Share of pixels agreeing to within f32 rounding — the residual
            // disagreement is concentrated in the high-gradient minority where
            // near-tied direction gradients can select differently.
            let agreeing = diffs.iter().filter(|&&d| d < 1.0e-6).count() as f64 / n;
            diffs.sort_by(f64::total_cmp);
            let med = diffs[diffs.len() / 2];
            let p999 = diffs[(diffs.len() as f64 * 0.999) as usize];
            println!(
                "plane {plane}: corr={corr:.6} median|d|={med:.3e} p99.9|d|={p999:.3e} \
                 agreeing={:.2}%",
                agreeing * 100.0
            );
            stats.push((corr, med));
        }
        // Report every plane before failing on any of them.
        for (plane, &(corr, med)) in stats.iter().enumerate() {
            // The median is the real oracle pin: it sits at f32 rounding, so more
            // than half the pixels match the reference bit for bit. Correlation is
            // only a coarse net for gross breakage (a channel swap or a wrong CFA
            // phase shows up here as an obvious failure). Its residual is tie-break
            // freedom, not error: on high-gradient pixels two directions' gradients
            // come out nearly equal and either may legitimately win, so bitwise
            // parity with another implementation was never expected.
            assert!(corr > 0.995, "plane {plane} corr {corr}");
            assert!(med < 2.0e-5, "plane {plane} median {med}"); // signal scale ~7e-3
        }
    }
}
